# 7. 데이터 선택 (loc)
이름을 이용하여 원하는 row 에서 원하는 col 선택

In [1]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [2]:
df.loc['1번'] # index 1번에 해당하는 전체 데이터

이름         채치수
학교         북산고
키          197
국어          90
영어          85
수학         100
과학          95
사회          85
SW특기    Python
Name: 1번, dtype: object

In [3]:
df.loc['5번'] # index 5번에 해당하는 전체 데이터

이름      강백호
학교      북산고
키       188
국어       15
영어       20
수학       10
과학       35
사회       10
SW특기    NaN
Name: 5번, dtype: object

In [4]:
df.loc['1번', '국어'] # index 1번에 해당하는 국어 데이터

90

In [5]:
df.loc[['1번', '2번'], '영어'] # index 1번, 2번에 해당하는 영어 데이터

지원번호
1번    85
2번    35
Name: 영어, dtype: int64

In [6]:
df.loc[['1번', '2번'], ['영어', '수학']] # index 1번, 2번에 해당하는 영어, 수학 데이터

      영어   수학
지원번호
1번    85  100
2번    35   50

In [7]:
df.loc['1번':'5번', '국어':'사회'] # index 1번부터 5번까지, 국어부터 사회까지 데이터

      국어  영어   수학  과학  사회
지원번호
1번    90  85  100  95  85
2번    40  35   50  55  25
3번    80  75   70  80  75
4번    40  60   70  75  80
5번    15  20   10  35  10

# 7. 데이터 선택 (loc)
데이서 선택 (loc) 요리조리

In [9]:
import pandas as pd
df1 = pd.read_excel('교육부_통합합급 현황.xlsx', index_col='시도교육청')
df1

,지역교육청,지역,정보공시학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,1학년,2학년,3학년,4학년,5학년,6학년,특수학급,순회학급,학급수(계),학생수(계),학급당학생수
시도교육청,,,,,,,,,,,,,,,,,,,
서울특별시교육청,교육부,서울특별시 서초구,S000003511,서울교육대학교부설초등학교,2,국립,N,NaN,4.0,4.0,4.0,5.0,5.0,5.0,1.0,0.0,28(1),612(5),21.86
서울특별시교육청,교육부,서울특별시 종로구,S000003563,서울대학교사범대학부설초등학교,2,국립,N,NaN,5.0,5.0,5.0,5.0,5.0,5.0,0.0,0.0,30(0),612(0),20.40
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000738,서울개일초등학교,2,공립,N,NaN,5.0,5.0,5.0,6.0,6.0,6.0,0.0,0.0,33(0),1078(0),32.67
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000741,서울구룡초등학교,2,공립,N,NaN,5.0,5.0,5.0,6.0,6.0,5.0,2.0,0.0,34(2),745(10),21.91
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000742,서울논현초등학교,2,공립,N,NaN,3.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,15(2),266(13),17.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000801,월랑초등학교,2,공립,N,NaN,3.0,4.0,4.0,5.0,5.0,5.0,1.0,0.0,27(1),664(4),24.59
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000834,이도초등학교,2,공립,N,NaN,7.0,6.0,7.0,8.0,7.0,8.0,1.0,0.0,44(1),1202(9),27.32
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000836,도련초등학교,2,공립,N,NaN,8.0,8.0,8.0,8.0,7.0,7.0,2.0,0.0,48(2),1213(10),25.27
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000837,삼화초등학교,2,공립,N,NaN,4.0,4.0,5.0,5.0,6.0,5.0,1.0,0.0,30(1),749(5),24.97
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000839,하귀일초등학교,2,공립,N,NaN,4.0,4.0,4.0,5.0,4.0,4.0,1.0,0.0,26(1),618(6),23.77

In [10]:
df2 = pd.read_excel('교육부_특수교육정보 특수학교 현황_20190924.xlsx', index_col='설립별')
df2

,장애별,학교 수,장애영아 학급 수,유치원 장애영아 학급 수,초등학교 장애영아 학급 수,중학교 장애영아 학급 수,고등학교 장애영아 학급 수,전공과 장애영아 학급 수,장애영아 학생 수,유치원 학생 수,초등학교 학생 수,중학교 학생 수,고등학교 학생 수,전공과 학생 수
설립별,,,,,,,,,,,,,,
국립,시각장애,1,2,4,7,8,11,7,6,17,20,33,73,52
국립,청각장애,1,3,4,6,10,11,0,7,6,14,30,57,0
국립,지적장애,1,0,1,12,6,6,5,0,2,70,36,41,40
국립,지체장애,1,0,3,14,8,10,4,0,10,60,32,45,16
국립,정서장애,1,0,3,12,6,6,6,0,9,58,36,41,44
공립,시각장애,2,0,3,9,6,14,7,0,9,30,25,83,54
공립,청각장애,3,3,7,18,9,10,6,7,30,53,37,45,60
공립,지적장애,63,3,67,621,502,578,280,16,219,2822,2746,3616,2416
공립,지체장애,5,2,7,74,54,46,18,9,22,321,256,240,127
공립,정서장애,1,0,2,9,7,10,4,0,10,41,40,54,28
사립,시각장애,9,1,10,54,30,55,26,2,34,178,131,321,178
사립,청각장애,10,11,23,62,45,49,11,48,87,254,220,276,82
사립,지적장애,55,17,101,404,265,297,123,56,384,1932,1572,1983,1024
사립,지체장애,12,3,16,103,67,61,11,11,64,472,401,426,79
사립,정서장애,5,0,9,47,36,42,20,0,35,260,223,276,187

In [11]:
df3 = pd.read_excel('장애영역별특수학급학생수집계현황.xlsx', index_col='기준년도')
df3

,장애영역명,총학생수(명),유치원전체학생수(명),유치원3세학생수(명),유치원4세학생수(명),유치원5세이상학생수(명),초등학교전체학생수(명),초등학교1학년학생수(명),초등학교2학년학생수(명),초등학교3학년학생수(명),...,중학교2학년학생수(명),중학교3학년학생수(명),고등학교전체학생수(명),고등학교1학년학생수(명),고등학교2학년학생수(명),고등학교3학년학생수(명),전공과전체학생수(명),전공과1년차학생수(명),전공과2년차학생수(명),전공과3년차학생수(명)
기준년도,,,,,,,,,,,,,,,,,,,,,
2022,건강장애,10,2,0,0,2,4,0,2,1,...,0,0,3,1,1,1,0,0,0,0
2022,발달지체,1399,893,189,348,356,506,192,209,105,...,0,0,0,0,0,0,0,0,0,0
2022,시각장애,67,3,0,3,0,33,6,3,2,...,6,5,19,6,6,7,0,0,0,0
2022,의사소통장애,381,60,5,14,41,293,66,47,52,...,6,5,7,2,2,3,2,1,1,0
2022,자폐성장애,2991,306,49,111,146,1860,385,326,278,...,160,151,337,114,117,106,10,4,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,정서행동장애,313,4,0,2,2,182,5,16,20,...,35,22,43,19,12,12,0,0,0,0
2012,지적장애,7328,83,8,27,48,3055,310,399,532,...,717,676,2059,779,694,586,18,14,4,0
2012,지체장애,1394,65,15,19,31,751,108,126,107,...,99,101,265,115,82,68,0,0,0,0
2012,청각장애,206,11,2,3,6,113,12,20,17,...,19,9,35,15,10,10,0,0,0,0
2012,학습장애,443,0,0,0,0,217,0,5,20,...,56,54,64,33,22,9,0,0,0,0

In [12]:
df4 = pd.read_excel('장애인 편의시설 현황(초).xlsx', index_col='시도교육청')
df4

,지역교육청,지역,정보공시학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,주 출입구 \n 접근로 설치여부,장애인 전용 \n 주차구역 지정여부,주출입구 \n 높이차이 제거여부,출입구(문) \n 설치유무,복도,계단/승강기/경사로 \n /휠체어리프트 유무,장애인용 \n 대변기 설치여부,장애인용 \n 소변기 설치여부,점자블록 \n 설치여부,유도 및 안내설비 \n 설치여부,경보 및 피난설비 \n 설치여부
시도교육청,,,,,,,,,,,,,,,,,,,
서울특별시교육청,교육부,서울특별시 서초구,S000003511,서울교육대학교부설초등학교,2,국립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,단순설치
서울특별시교육청,교육부,서울특별시 종로구,S000003563,서울대학교사범대학부설초등학교,2,국립,N,NaN,단순설치,단순설치,적정설치,단순설치,적정설치,적정설치,적정설치,단순설치,단순설치,적정설치,적정설치
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000738,서울개일초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,미설치
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000741,서울구룡초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000742,서울논현초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000801,월랑초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,단순설치,적정설치,적정설치,적정설치,적정설치,단순설치,단순설치,적정설치
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000834,이도초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000836,도련초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000837,삼화초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000839,하귀일초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치

In [13]:
df1.loc['서울특별시교육청']

,지역교육청,지역,정보공시학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,1학년,2학년,3학년,4학년,5학년,6학년,특수학급,순회학급,학급수(계),학생수(계),학급당학생수
시도교육청,,,,,,,,,,,,,,,,,,,
서울특별시교육청,교육부,서울특별시 서초구,S000003511,서울교육대학교부설초등학교,2,국립,N,NaN,4.0,4.0,4.0,5.0,5.0,5.0,1.0,0.0,28(1),612(5),21.86
서울특별시교육청,교육부,서울특별시 종로구,S000003563,서울대학교사범대학부설초등학교,2,국립,N,NaN,5.0,5.0,5.0,5.0,5.0,5.0,0.0,0.0,30(0),612(0),20.40
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000738,서울개일초등학교,2,공립,N,NaN,5.0,5.0,5.0,6.0,6.0,6.0,0.0,0.0,33(0),1078(0),32.67
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000741,서울구룡초등학교,2,공립,N,NaN,5.0,5.0,5.0,6.0,6.0,5.0,2.0,0.0,34(2),745(10),21.91
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000742,서울논현초등학교,2,공립,N,NaN,3.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,15(2),266(13),17.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
서울특별시교육청,서울특별시남부교육지원청,서울특별시 구로구,S010006431,서울하늘숲초등학교,2,공립,N,NaN,4.0,4.0,6.0,6.0,6.0,5.0,2.0,0.0,33(2),629(8),19.06
서울특별시교육청,서울특별시남부교육지원청,서울특별시 구로구,S010006432,서울항동초등학교,2,공립,N,NaN,12.0,10.0,9.0,7.0,7.0,6.0,2.0,0.0,53(2),1165(9),21.98
서울특별시교육청,서울특별시강동송파교육지원청,서울특별시 송파구,S010006433,서울해누리초등학교,2,공립,N,NaN,5.0,5.0,4.0,5.0,5.0,3.0,1.0,0.0,28(1),610(5),21.79
서울특별시교육청,서울특별시동부교육지원청,서울특별시 중랑구,S010006476,서울양원숲초등학교,2,공립,N,NaN,5.0,4.0,3.0,3.0,2.0,2.0,1.0,0.0,20(1),377(4),18.85
서울특별시교육청,서울특별시강동송파교육지원청,서울특별시 강동구,S010006543,서울강빛초등학교,2,공립,N,NaN,7.0,6.0,5.0,5.0,4.0,4.0,1.0,0.0,32(1),571(2),17.84

In [14]:
df2.loc['국립']

,장애별,학교 수,장애영아 학급 수,유치원 장애영아 학급 수,초등학교 장애영아 학급 수,중학교 장애영아 학급 수,고등학교 장애영아 학급 수,전공과 장애영아 학급 수,장애영아 학생 수,유치원 학생 수,초등학교 학생 수,중학교 학생 수,고등학교 학생 수,전공과 학생 수
설립별,,,,,,,,,,,,,,
국립,시각장애,1,2,4,7,8,11,7,6,17,20,33,73,52
국립,청각장애,1,3,4,6,10,11,0,7,6,14,30,57,0
국립,지적장애,1,0,1,12,6,6,5,0,2,70,36,41,40
국립,지체장애,1,0,3,14,8,10,4,0,10,60,32,45,16
국립,정서장애,1,0,3,12,6,6,6,0,9,58,36,41,44

In [16]:
df3.loc[2022]

,장애영역명,총학생수(명),유치원전체학생수(명),유치원3세학생수(명),유치원4세학생수(명),유치원5세이상학생수(명),초등학교전체학생수(명),초등학교1학년학생수(명),초등학교2학년학생수(명),초등학교3학년학생수(명),...,중학교2학년학생수(명),중학교3학년학생수(명),고등학교전체학생수(명),고등학교1학년학생수(명),고등학교2학년학생수(명),고등학교3학년학생수(명),전공과전체학생수(명),전공과1년차학생수(명),전공과2년차학생수(명),전공과3년차학생수(명)
기준년도,,,,,,,,,,,,,,,,,,,,,
2022,건강장애,10,2,0,0,2,4,0,2,1,...,0,0,3,1,1,1,0,0,0,0
2022,발달지체,1399,893,189,348,356,506,192,209,105,...,0,0,0,0,0,0,0,0,0,0
2022,시각장애,67,3,0,3,0,33,6,3,2,...,6,5,19,6,6,7,0,0,0,0
2022,의사소통장애,381,60,5,14,41,293,66,47,52,...,6,5,7,2,2,3,2,1,1,0
2022,자폐성장애,2991,306,49,111,146,1860,385,326,278,...,160,151,337,114,117,106,10,4,6,0
2022,정서행동장애,273,0,0,0,0,125,7,8,17,...,25,39,62,16,20,26,1,1,0,0
2022,지적장애,9571,165,17,42,106,4891,605,665,779,...,765,755,2161,717,753,691,120,62,58,0
2022,지체장애,1176,165,45,53,67,548,103,97,88,...,68,77,251,91,81,79,4,3,1,0
2022,청각장애,183,17,2,10,5,100,12,12,18,...,14,17,28,6,10,12,0,0,0,0
2022,학습장애,141,0,0,0,0,70,0,4,6,...,8,15,37,12,12,13,0,0,0,0

In [18]:
df4.loc['서울특별시교육청']

,지역교육청,지역,정보공시학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,주 출입구 \n 접근로 설치여부,장애인 전용 \n 주차구역 지정여부,주출입구 \n 높이차이 제거여부,출입구(문) \n 설치유무,복도,계단/승강기/경사로 \n /휠체어리프트 유무,장애인용 \n 대변기 설치여부,장애인용 \n 소변기 설치여부,점자블록 \n 설치여부,유도 및 안내설비 \n 설치여부,경보 및 피난설비 \n 설치여부
시도교육청,,,,,,,,,,,,,,,,,,,
서울특별시교육청,교육부,서울특별시 서초구,S000003511,서울교육대학교부설초등학교,2,국립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,단순설치
서울특별시교육청,교육부,서울특별시 종로구,S000003563,서울대학교사범대학부설초등학교,2,국립,N,NaN,단순설치,단순설치,적정설치,단순설치,적정설치,적정설치,적정설치,단순설치,단순설치,적정설치,적정설치
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000738,서울개일초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,미설치
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000741,서울구룡초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000742,서울논현초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
서울특별시교육청,서울특별시남부교육지원청,서울특별시 구로구,S010006431,서울하늘숲초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
서울특별시교육청,서울특별시남부교육지원청,서울특별시 구로구,S010006432,서울항동초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
서울특별시교육청,서울특별시강동송파교육지원청,서울특별시 송파구,S010006433,서울해누리초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
서울특별시교육청,서울특별시동부교육지원청,서울특별시 중랑구,S010006476,서울양원숲초등학교,2,공립,N,NaN,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치,적정설치
서울특별시교육청,서울특별시강동송파교육지원청,서울특별시 강동구,S010006543,서울강빛초등학교,2,공립,Y,이음학교로 중학교에서 입력하는 사항임,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df1.loc['서울특별시교육청', '지역교육청']

시도교육청
서울특별시교육청               교육부
서울특별시교육청               교육부
서울특별시교육청    서울특별시강남서초교육지원청
서울특별시교육청    서울특별시강남서초교육지원청
서울특별시교육청    서울특별시강남서초교육지원청
                 ...
서울특별시교육청      서울특별시남부교육지원청
서울특별시교육청      서울특별시남부교육지원청
서울특별시교육청    서울특별시강동송파교육지원청
서울특별시교육청      서울특별시동부교육지원청
서울특별시교육청    서울특별시강동송파교육지원청
Name: 지역교육청, Length: 605, dtype: object

In [22]:
df2.loc['국립', '장애별']

설립별
국립    시각장애
국립    청각장애
국립    지적장애
국립    지체장애
국립    정서장애
Name: 장애별, dtype: object

In [23]:
df3.loc[2022, '장애영역명']

기준년도
2022      건강장애
2022      발달지체
2022      시각장애
2022    의사소통장애
2022     자폐성장애
2022    정서행동장애
2022      지적장애
2022      지체장애
2022      청각장애
2022      학습장애
Name: 장애영역명, dtype: object

In [24]:
df4.loc['서울특별시교육청', '지역교육청']

시도교육청
서울특별시교육청               교육부
서울특별시교육청               교육부
서울특별시교육청    서울특별시강남서초교육지원청
서울특별시교육청    서울특별시강남서초교육지원청
서울특별시교육청    서울특별시강남서초교육지원청
                 ...
서울특별시교육청      서울특별시남부교육지원청
서울특별시교육청      서울특별시남부교육지원청
서울특별시교육청    서울특별시강동송파교육지원청
서울특별시교육청      서울특별시동부교육지원청
서울특별시교육청    서울특별시강동송파교육지원청
Name: 지역교육청, Length: 605, dtype: object

In [25]:
df1.loc[['서울특별시교육청', '제주특별자치도교육청'], '지역교육청']

시도교육청
서울특별시교육청                 교육부
서울특별시교육청                 교육부
서울특별시교육청      서울특별시강남서초교육지원청
서울특별시교육청      서울특별시강남서초교육지원청
서울특별시교육청      서울특별시강남서초교육지원청
                   ...
제주특별자치도교육청          제주시교육지원청
제주특별자치도교육청          제주시교육지원청
제주특별자치도교육청          제주시교육지원청
제주특별자치도교육청          제주시교육지원청
제주특별자치도교육청          제주시교육지원청
Name: 지역교육청, Length: 723, dtype: object

In [27]:
df2.loc[['국립', '공립'], '장애별']

설립별
국립    시각장애
국립    청각장애
국립    지적장애
국립    지체장애
국립    정서장애
공립    시각장애
공립    청각장애
공립    지적장애
공립    지체장애
공립    정서장애
Name: 장애별, dtype: object

In [28]:
df3.loc[[2022, 2021], '장애영역명']

기준년도
2022      건강장애
2022      발달지체
2022      시각장애
2022    의사소통장애
2022     자폐성장애
2022    정서행동장애
2022      지적장애
2022      지체장애
2022      청각장애
2022      학습장애
2021      건강장애
2021      발달지체
2021      시각장애
2021    의사소통장애
2021     자폐성장애
2021    정서행동장애
2021      지적장애
2021      지체장애
2021      청각장애
2021      학습장애
Name: 장애영역명, dtype: object

In [29]:
df4.loc[['서울특별시교육청', '제주특별자치도교육청'], '지역교육청']

시도교육청
서울특별시교육청                 교육부
서울특별시교육청                 교육부
서울특별시교육청      서울특별시강남서초교육지원청
서울특별시교육청      서울특별시강남서초교육지원청
서울특별시교육청      서울특별시강남서초교육지원청
                   ...
제주특별자치도교육청          제주시교육지원청
제주특별자치도교육청          제주시교육지원청
제주특별자치도교육청          제주시교육지원청
제주특별자치도교육청          제주시교육지원청
제주특별자치도교육청          제주시교육지원청
Name: 지역교육청, Length: 723, dtype: object

In [30]:
df1.loc[['서울특별시교육청', '제주특별자치도교육청'], ['지역교육청', '지역']]

                     지역교육청           지역
시도교육청
서울특별시교육청               교육부    서울특별시 서초구
서울특별시교육청               교육부    서울특별시 종로구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
...                    ...          ...
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시

[723 rows x 2 columns]

In [31]:
df2.loc[['국립', '공립'], ['장애별', '학교 수']]

      장애별  학교 수
설립별
국립   시각장애     1
국립   청각장애     1
국립   지적장애     1
국립   지체장애     1
국립   정서장애     1
공립   시각장애     2
공립   청각장애     3
공립   지적장애    63
공립   지체장애     5
공립   정서장애     1

In [32]:
df3.loc[[2022, 2021], ['장애영역명', '총학생수(명)']]

       장애영역명  총학생수(명)
기준년도
2022    건강장애       10
2022    발달지체     1399
2022    시각장애       67
2022  의사소통장애      381
2022   자폐성장애     2991
2022  정서행동장애      273
2022    지적장애     9571
2022    지체장애     1176
2022    청각장애      183
2022    학습장애      141
2021    건강장애       15
2021    발달지체     1079
2021    시각장애       76
2021  의사소통장애      362
2021   자폐성장애     2569
2021  정서행동장애      281
2021    지적장애     8965
2021    지체장애     1162
2021    청각장애      196
2021    학습장애       31

In [33]:
df4.loc[['서울특별시교육청', '제주특별자치도교육청'], ['지역교육청', '지역']]

                     지역교육청           지역
시도교육청
서울특별시교육청               교육부    서울특별시 서초구
서울특별시교육청               교육부    서울특별시 종로구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
...                    ...          ...
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시

[723 rows x 2 columns]

In [38]:
df1.loc['서울특별시교육청':'제주특별자치도교육청', '지역교육청':'지역']

                     지역교육청           지역
시도교육청
서울특별시교육청               교육부    서울특별시 서초구
서울특별시교육청               교육부    서울특별시 종로구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
...                    ...          ...
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시

[6309 rows x 2 columns]

In [39]:
df2.loc['국립':'공립', '장애별':'학교 수']

      장애별  학교 수
설립별
국립   시각장애     1
국립   청각장애     1
국립   지적장애     1
국립   지체장애     1
국립   정서장애     1
공립   시각장애     2
공립   청각장애     3
공립   지적장애    63
공립   지체장애     5
공립   정서장애     1

In [40]:
df3.loc[2022:2021, '장애영역명':'총학생수(명)']

       장애영역명  총학생수(명)
기준년도
2022    건강장애       10
2022    발달지체     1399
2022    시각장애       67
2022  의사소통장애      381
2022   자폐성장애     2991
2022  정서행동장애      273
2022    지적장애     9571
2022    지체장애     1176
2022    청각장애      183
2022    학습장애      141
2021    건강장애       15
2021    발달지체     1079
2021    시각장애       76
2021  의사소통장애      362
2021   자폐성장애     2569
2021  정서행동장애      281
2021    지적장애     8965
2021    지체장애     1162
2021    청각장애      196
2021    학습장애       31

In [41]:
df4.loc['서울특별시교육청':'제주특별자치도교육청', '지역교육청':'지역']

                     지역교육청           지역
시도교육청
서울특별시교육청               교육부    서울특별시 서초구
서울특별시교육청               교육부    서울특별시 종로구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
서울특별시교육청    서울특별시강남서초교육지원청    서울특별시 강남구
...                    ...          ...
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시
제주특별자치도교육청        제주시교육지원청  제주특별자치도 제주시

[6309 rows x 2 columns]